when:
  - event: push
  - event: pull_request

clone:
  git:
    image: bash
    settings:
      lfs: false

steps:
  build:
    image: bash
    commands:
      - nix --accept-flake-config build .#default

  deploy:
    image: bash
    when:
      - event: push
        branch: main
    commands:
      - deploy-flake-input ony-world "$CI_COMMIT_SHA"
