when:
  - event: push
  - event: pull_request

steps:
  build:
    image: local
    commands:
      - nix --accept-flake-config build .#default

  deploy:
    image: local
    when:
      - event: push
        branch: main
    commands:
      - sudo deploy-flake-input ony-world "$CI_COMMIT_SHA"
